CREATE TABLE IF NOT EXISTS Person (
  ID INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(32) NOT NULL,
  lastName VARCHAR(32) NOT NULL,
  email VARCHAR(64) NOT NULL,
  type ENUM('STUDENT', 'TUTOR', 'SUPERVISIOR') DEFAULT 'STUDENT',
  PRIMARY KEY(ID));
  
CREATE TABLE IF NOT EXISTS Courses (
  courseID VARCHAR(8) NOT NULL,
  description VARCHAR(32) NOT NULL,
  PRIMARY KEY(courseID)
);

CREATE TABLE IF NOT EXISTS CoursesTutored (
  tutorID INT NOT NULL,
  courseID VARCHAR(8) NOT NULL,
  FOREIGN KEY(tutorID) REFERENCES Person(ID) ON DELETE CASCADE,
  FOREIGN KEY(courseID) REFERENCES Courses(courseID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Appointment (
  ID INT NOT NULL AUTO_INCREMENT,
  startTime DATETIME NOT NULL,
  endTime DATETIME NOT NULL,
  tutor INT NOT NULL,
  student INT,
  course VARCHAR(8),
  PRIMARY KEY (ID),
  FOREIGN KEY(tutor) REFERENCES Person(ID) ON DELETE CASCADE,
  FOREIGN KEY(student) REFERENCES Person(ID) ON DELETE CASCADE,
  FOREIGN KEY(course) REFERENCES Courses(courseID) ON DELETE CASCADE
);
  
